### ISSUE TITLE
Invalid Form Body

### ISSUE THREAD

**Issue by Maldohr** [MMPlugins/HexedHelp#2]
Hi,
if i put the english language in it fits perfect. But if i put another language as default (in my case german), i get this error in console:

```
Error 50035: DiscordRESTError [50035]: Invalid Form Body
embed.description: Must be 2048 or fewer in length.
```

What i did wrong?

**Comment by hexed** [comment]
So there is a limitation with how long the embeds can be. I am looking into alternative options.

**Comment by hexed** [comment]
If you can try to condense it. It will work. While I work on fixing pagination.

**Comment by hexed** [comment]
This has been mitigated and fixed. In the experimental branch.
